server:
  port: 9000

spring:
  threads:
    virtual:
      enabled: true
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: XXX
#    password: XXX
#    url: XXXX
  jpa:
    hibernate.ddl-auto: create-drop
  kafka:
    producer:
#      bootstrap-servers: XXXX
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      transaction-id-prefix: tx-
